version: 0.2

env:
  parameter-store:
    IGN: "/CodeBuild/td"

phases:
  install:
    commands:
      - echo "This is Installation Phase"
      - echo "$IGN"
  pre_build:      
    commands:
      - echo "$IGN"
      - echo "The Pre-Build is running good"
  build:
    commands:
      - echo $IGN
      - echo "The build phase is runnig good"
  post_build:
    commands:
      - echo $IGN
      - echo "This is Post Build Phase"
