version: 0.2

phases:
  install:
    commands:
      - echo "This is Installation Phase"
  pre_build:      
    commands:
      - echo "This is the Pre-Build Phase"
      - echo "The Pre-Build is running good"
  build:
    commands:
      - echo "This is the Build Phase..."
      - echo "The build phase is runnig good"
  post_build:
    commands:
      - echo "This is Post Build Phase"
      - echo "End of CodeBuild"
