version: 0.2

env:
  parameter-store:
  IGN: /tanumoy/var

phases:
  install:
    commands:
      - echo "This is Installation Phase"
  pre_build:      
    commands:
      - echo "The Pre-Build is running good"
  build:
    commands:
      - echo $IGN 
      - echo "The build phase is runnig good"
  post_build:
    commands:
      - echo "This is Post Build Phase"
      - echo "End of CodeBuild"
