version: 0.2

phases:
  install:
    commands:
      - echo "This is Installation Phase"
      - echo "$DB_PASS"
  pre_build:      
    commands:
      - echo "$DB_PASS"
      - echo "The Pre-Build is running good"
      - printenv
  build:
    commands:
      - echo $DB_PASS
      - echo "The build phase is runnig good"
  post_build:
    commands:
      - echo $DB_PASS
      - echo "This is Post Build Phase"
